### ISSUE TITLE
新建多页模版运行出错

### ISSUE THREAD

**Issue by terily** [lavas-project/lavas#11]
Starting to optimize CSS...
    ./node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?{"minimize":false,"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-f8e1795c","scoped":true,"hasInlineConfig":false}!./node_modules/stylus-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./build/loaders/theme-loader.js?{"injectInVueFile":true}!./src/pages/detail/Detail.skeleton.vue
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/ll/project/web/mpa-simple/node_modules/extract-text-webpack-plugin/loader.js:25:9)
    @ ./src/pages/detail/Detail.skeleton.vue 3:4-489
    @ ./src/pages/detail/entry-skeleton.js

    /Users/ll/project/web/mpa-simple/node_modules/memory-fs/lib/MemoryFileSystem.js:114
			throw new MemoryFileSystemError(errors.code.ENOENT, _path);
			^
    Error
        at MemoryFileSystem.readFileSync (/Users/ll/project/web/mpa-simple/node_modules/memory-fs/lib/MemoryFileSystem.js:114:10)
        at Watching.handler (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/lib/ssr.js:50:31)
        at Watching._done (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/Compiler.js:105:8)
        at compiler.emitRecords.err (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/Compiler.js:78:19)
        at Compiler.emitRecords (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/Compiler.js:375:38)
        at compiler.emitAssets.err (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/Compiler.js:61:20)
        at applyPluginsAsyncSeries1.err (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/Compiler.js:368:12)
        at next (/Users/ll/project/web/mpa-simple/node_modules/tapable/lib/Tapable.js:218:11)
        at Compiler.compiler.plugin (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
        at Compiler.applyPluginsAsyncSeries1 (/Users/ll/project/web/mpa-simple/node_modules/tapable/lib/Tapable.js:222:13)
        at Compiler.afterEmit (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/Compiler.js:365:9)
        at require.forEach.err (/Users/ll/project/web/mpa-simple/node_modules/vue-skeleton-webpack-plugin/node_modules/webpack/lib/Compiler.js:354:15)
        at /Users/ll/project/web/mpa-simple/node_modules/async/dist/async.js:421:16
        at iteratorCallback (/Users/ll/project/web/mpa-simple/node_modules/async/dist/async.js:998:13)
        at /Users/ll/project/web/mpa-simple/node_modules/async/dist/async.js:906:16
        at MemoryFileSystem.writeFile (/Users/ll/project/web/mpa-simple/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! mpa-simple@1.0.0 dev: `node build/dev-server.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the mpa-simple@1.0.0 dev script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

项目是直接用lavas init 创建的多页模板，什么都没改直接运行  npm run dev 就报错了。
各个模块的版本为：
 
    npm: 5.3.0
    lavas: 1.0.7
    node: 8.4.0

**Comment by xiaoiver** [comment]
这个问题和 #10 是同一个，我昨天改过了，重新用命令行创建一个项目就行了
