### ISSUE TITLE
新版 vue-skeleton-webpack-plugin 会报错

### ISSUE THREAD

**Issue by PengXing** [lavas-project/lavas#160]
`vue-skeleton-webpack-plugin@1.1.16` 版本导致 `lavas dev` 启动的时候报错了

```
➜  pwa-project npm run dev

> pwa-project@0.0.1 dev /Users/sekiyika/temp/pwa-project
> lavas dev

LAVAS INFO 正在启动 Lavas 调试服务器...
✔ [Lavas build] reading config completed.
✔ [Lavas build] compiling routes completed.
✔ [Lavas build] writing files to /.lavas completed
  [==================  ] 91% (10.5 seconds)/Users/sekiyika/temp/pwa-project/node_modules/vue-skeleton-webpack-plugin/lib/ssr.js:75
                var skeletonCss = childCompilation.assets[outputCSSPath].source();
                                                                         ^

TypeError: Cannot read property 'source' of undefined
    at /Users/sekiyika/temp/pwa-project/node_modules/vue-skeleton-webpack-plugin/lib/ssr.js:75:74
    at compile (/Users/sekiyika/temp/pwa-project/node_modules/webpack/lib/Compiler.js:300:11)
    at applyPluginsAsync.err (/Users/sekiyika/temp/pwa-project/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/Users/sekiyika/temp/pwa-project/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/Users/sekiyika/temp/pwa-project/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/Users/sekiyika/temp/pwa-project/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/Users/sekiyika/temp/pwa-project/node_modules/webpack/lib/Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (/Users/sekiyika/temp/pwa-project/node_modules/tapable/lib/Tapable.js:195:46)
    at applyPluginsAsync.err (/Users/sekiyika/temp/pwa-project/node_modules/webpack/lib/Compilation.js:683:19)
    at Compilation.applyPluginsAsyncSeries (/Users/sekiyika/temp/pwa-project/node_modules/tapable/lib/Tapable.js:195:46)
    at applyPluginsAsync.err (/Users/sekiyika/temp/pwa-project/node_modules/webpack/lib/Compilation.js:674:11)
    at Compilation.applyPluginsAsyncSeries (/Users/sekiyika/temp/pwa-project/node_modules/tapable/lib/Tapable.js:195:46)
    at applyPluginsAsync.err (/Users/sekiyika/temp/pwa-project/node_modules/webpack/lib/Compilation.js:669:10)
    at next (/Users/sekiyika/temp/pwa-project/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/sekiyika/temp/pwa-project/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (/Users/sekiyika/temp/pwa-project/node_modules/tapable/lib/Tapable.js:206:13)
```

**Comment by PengXing** [comment]
升级到新版 `vue-skeleton-webpack-plugin` 已解决
