### ISSUE TITLE
lavas init报错 拉取云端数据403

### ISSUE THREAD

**Issue by wandiao** [lavas-project/lavas#239]
![image](https://user-images.githubusercontent.com/23516461/69722740-cc40a300-1152-11ea-976c-529b2ed7f587.png)
大佬麻烦看看什么原因造成的

lavas版本: 2.2.12
系统版本：macOS10.14

**Comment by ffable** [comment]
[https://github.com/lavas-project/lavas/blob/master/packages/lavas-cli/src/lib/scaffold/config.js](https://github.com/lavas-project/lavas/blob/master/packages/lavas-cli/src/lib/scaffold/config.js)

因为云端bos.nj.bpc.baidu.com Http 403

根据这两个项目自建吧
[https://github.com/lavas-project/lavas-template-vue](https://github.com/lavas-project/lavas-template-vue)
[https://github.com/lavas-project/lavas-config](https://github.com/lavas-project/lavas-config)

**Comment by wandiao** [comment]
行吧。。，那这个问题什么时候能修复呢

**Comment by handsome-yang** [comment]
macOS10.15.1


⠋ 正在拉取云端数据，请稍候...(node:12410) UnhandledPromiseRejectionWarning: StatusCodeError: 403 - {"code":"Http403","message":"403 Forbidden","requestId":"52454655-5345-4420-4259-204e47494e58"}
    at new StatusCodeError (/usr/local/lib/node_modules/lavas/node_modules/_request-promise-core@1.1.3@request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/lavas/node_modules/_request-promise-core@1.1.3@request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/lavas/node_modules/_request-promise-core@1.1.3@request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/lavas/node_modules/_request@2.88.0@request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/local/lib/node_modules/lavas/node_modules/_request@2.88.0@request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/lavas/node_modules/_request@2.88.0@request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:12410) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12410) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
