### ISSUE TITLE
lavas dev后报错

### ISSUE THREAD

**Issue by SimThread** [lavas-project/lavas#26]
按照官网的提示操作lavas dev时，报以下错误
```
ReferenceError: DEFAULT_ENTRY_NAME is not defined
    at DevBuilder.addSkeletonRoutes (/Users/mac/Desktop/cx-project/project/my-demo/4-demo/pwa-project/node_modules/_lavas@2.1.1@lavas/dist/core/builder/dev-builder.js:130:25)
    at DevBuilder._callee4$ (/Users/mac/Desktop/cx-project/project/my-demo/4-demo/pwa-project/node_modules/_lavas@2.1.1@lavas/dist/core/builder/dev-builder.js:346:36)
    at tryCatch (/Users/mac/Desktop/cx-project/project/my-demo/4-demo/pwa-project/node_modules/_regenerator-runtime@0.11.1@regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mac/Desktop/cx-project/project/my-demo/4-demo/pwa-project/node_modules/_regenerator-runtime@0.11.1@regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mac/Desktop/cx-project/project/my-demo/4-demo/pwa-project/node_modules/_regenerator-runtime@0.11.1@regenerator-runtime/runtime.js:114:21)
    at step (/Users/mac/Desktop/cx-project/project/my-demo/4-demo/pwa-project/node_modules/_babel-runtime@6.26.0@babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/mac/Desktop/cx-project/project/my-demo/4-demo/pwa-project/node_modules/_babel-runtime@6.26.0@babel-runtime/helpers/asyncToGenerator.js:28:13

```
尝试了Basic和AppShell都会报这个错误

**环境**
mac
node.js v7.2.1
npm 3.10.10
LAVAS INFO version:  2.1.0-rc.5

**Comment by easonyq** [comment]
您好，是我们lavas首页的安装步骤显示有问题，导致了您安装了我们的测试版本，而非正式上线版本。

您是否使用了 `npm install lavas@lavas2 -g` ?

正确线上版本应该是 `npm install lavas -g` 。lavas的最新版本应当是 2.1.4 而非 2.1.0-rc5

我们会及时修改首页上的错误，多谢您的回复！

**Comment by SimThread** [comment]
谢谢！改为```npm install lavas -g```后可以正常启动了
