### ISSUE TITLE
Appshell版本，装机后，lavas dev报错，node版本v5.1.1

### ISSUE THREAD

**Issue by liuhuatao** [lavas-project/lavas#65]
详细错误：/usr/local/mongodb/bin/helloword/server.dev.js:12
let configPath = './lavas.config.js';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

**Comment by PengXing** [comment]
你 Node.js 版本似乎有点老，啥版本的？

**Comment by liuhuatao** [comment]
建议在readme里面写上支持的版本

**Comment by PengXing** [comment]
好的，今天会补充一下，谢谢提醒
